### ISSUE TITLE
Make Calico self-hosted

### ISSUE THREAD

**Issue by nhlfr** [giantswarm/k8scloudconfig#40]
Make Calico self-hosted

http://docs.projectcalico.org/v2.0/getting-started/kubernetes/installation/hosted/

Currently we set up Calico with systemd units, without using containers, and with downloading binaries as a part of systemd unit, which really should be changed!

**Comment by puja108** [comment]
+1

I'm fiddling around looking into upgrading to a recent version (2.1.1+ needed for k8s 1.6+) and it's quite a mindfuck like it is right now.

**Comment by calvix** [comment]
We already running calico as k8s pod in g8s itself on aws so i would recommend copy anything necessary for that configuration !

https://github.com/giantswarm/gsegg/blob/initial_version/template-manifests/calico-node.yaml

**Comment by puja108** [comment]
cool

**Comment by puja108** [comment]
Looked further into it and etcdless might not be good for now, there's stuff missing like calico bgp itself and lot of other functionality, it only does policy enforcement. We should use http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/hosted for now

**Comment by puja108** [comment]
I can get this running already. Some issues I still have:

- There's one thing we need to check, currently the etcd TLS setup is through a secret, I manually fiddled our certs in there, but we need to automate that secret creation (the secret needs to be in `kube-system` inside guest k8s). 
- Currently, the DS only schedules to one node, not sure what is goign wrong with the discovery of the second node.
- The DS should additionally schedule to the master node, but as we currently do not have a kubelet running there it can't, so we would need to have at least a kubelet running, even if we don't move to self-hosted yet.

**Comment by puja108** [comment]
I tried it out on a local 2 worker vagrant setup with k8s 1.5.5 and got it working, so in general it should work with our setup considering the above points (especially 1 and 3) solved

**Comment by calvix** [comment]
@puja108 we run kubelet on core machines so that is fine, we jsut ahve to ahve different labels so on workers kubelet  an core kubelet

**Comment by nhlfr** [comment]
Unfortunately, in k8scloudconfig we don't run kubelet on masters yet, we need to change that when implementing hosted installation.

**Comment by puja108** [comment]
The master kubelet should be tainted, and the calico DS has a toleration for that taint.

**Comment by puja108** [comment]
just as a sidenote: we could run a kubelet on masters, even without goign full self-hosted k8s

**Comment by puja108** [comment]
needs https://github.com/giantswarm/k8scloudconfig/issues/116

**Comment by puja108** [comment]
Based on http://docs.projectcalico.org/v2.1/getting-started/kubernetes/installation/hosted/calico.yaml my current status is (needs templating):

```
# Calico Version v2.1.5
# http://docs.projectcalico.org/v2.1/releases#v2.1.5
# This manifest includes the following component versions:
#   calico/node:v1.1.3
#   calico/cni:v1.8.0
#   calico/kube-policy-controller:v0.5.4

# This ConfigMap is used to configure a self-hosted Calico installation.
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  # Configure this with the location of your etcd cluster.
  etcd_endpoints: "https://etcd.l8.k8s.gigantic.io:443"

  # Configure the Calico backend to use.
  calico_backend: "bird"

  # The CNI network configuration to install on each node.
  cni_network_config: |-
    {
        "name": "k8s-pod-network",
        "type": "calico",
        "etcd_endpoints": "__ETCD_ENDPOINTS__",
        "etcd_key_file": "__ETCD_KEY_FILE__",
        "etcd_cert_file": "__ETCD_CERT_FILE__",
        "etcd_ca_cert_file": "__ETCD_CA_CERT_FILE__",
        "log_level": "info",
        "ipam": {
            "type": "calico-ipam"
        },
        "policy": {
            "type": "k8s",
            "k8s_api_root": "https://__KUBERNETES_SERVICE_HOST__:__KUBERNETES_SERVICE_PORT__",
            "k8s_auth_token": "__SERVICEACCOUNT_TOKEN__"
        },
        "kubernetes": {
            "kubeconfig": "__KUBECONFIG_FILEPATH__"
        }
    }

  # If you're using TLS enabled etcd uncomment the following.
  # You must also populate the Secret below with these files.
  etcd_ca: "/calico-secrets/etcd-ca"
  etcd_cert: "/calico-secrets/etcd-cert"
  etcd_key: "/calico-secrets/etcd-key"

---

# The following contains k8s Secrets for use with a TLS enabled etcd cluster.
# For information on populating Secrets, see http://kubernetes.io/docs/user-guide/secrets/
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: calico-etcd-secrets
  namespace: kube-system
data:
  # Populate the following files with etcd TLS configuration if desired, but leave blank if
  # not using TLS for etcd.
  # This self-hosted install expects three files with the following names.  The values
  # should be base64 encoded strings of the entire contents of each file.
  etcd-key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQ0KTUlJRXBnSUJBQUtDQVFFQTRES3RGNytvZzVDM3lSUklMd2d1S2xualRlb2EzdzdVaGsvcXA0R1g2WGU5Rml3NQ0KWDRYdGZoR2tIL3RhSUpnaUY2ZzlQSkw0WGNLdHk0Qi9kNk13ZDJMTGNma0t4aVdNcWxVUnMxV2pYM3hKY1AraQ0KcUpxSlJXU0kvbG8weGhya29ZUzg4S2NZNVIxYkpJUzlZeHFLdGNQLzJBaDRPNVo4WlNBdDZSNHRPRS9LNjlWOQ0KOE95ZHJ3OFBKcjJYTk5Tb2VyYmQ2RUZrcWpEc1hQbjBQMFNPdUN0SnZlcGdCRXhBbGtscTNLVnhTeUx5amhBZQ0KVzN2bFJ0VkNhNFhMQnRmRU9rYVY0d2JJY2ZocERTU2RxVXJFOHhGbllXRnh5ZitTRHZlNUpFQ29YcTZGREhCdQ0KRHVXbW1YU2RMNGV0MVVOY2pXVHByYzQwd1ZVT3BVWjZidXlxYXdJREFRQUJBb0lCQVFEY0hRVFNGeXBFR1ZaSA0KUmZGa3M1eFhtaTdQZFROeW9lWElCRGcyd3NZNXdvUlRlNUhNbGZuSVYxdVN4cjBDMlRwSGpiYXBmUVg1VDhRLw0KMHVYU3VOWkJzQzVidEkxK1lxbExKZ0FkMk10d1dON2w0U1Y2Y1ZhcVdYMGljNy95YTc3aVVTY0xBcE12aG5YUQ0KVWI1NnlUazhJYlZURFdXMTR4WTRWcktjZURNZlgyaFdzQXZvNENaZnVpZzcwQU1PVzJDTVRXT2k1RlI4dm9WcQ0KWnRCc2J0OUtreU1pTFVmT1RZY1dhOFNuMExMbVd1Y0NXOTJoRllrSDFTZ2ZqZml2Vkl4SjJKb2paSFBvaWxDaw0KNkZNWU1maDhRSnZZSkRWQnpjcDl3RkhxRGxMaTBjeXBwbTQ2NU92QnlCWTFOTVhSeVhueDh3YXFmVkJZZGZzQQ0KVVpuTEtUK3hBb0dCQVA4NHRCVE5LSm13ZkNheHNoRUtkSUNNQlF0UFBsZHJtbjhVVUp1Znd0d3dKMHp6L1ltQQ0KL0drRkxmZnZOZkJZcVJvSEFVamtzUTdtK29UNmxsT3BpT0NUWlplbEZMNVRKeEZnTCtlMHZQRlQrMXA5VnRrLw0KeStMZVA5SXptRy9rMEtibTJqSGk2VFVTVVY2OWZBc3gyZVFqZXl1eGxaVTBIaVFnTlBoTFNkTXBBb0dCQU9EaA0KdjBRc2xBWVlmU1VUa2dnZm9hZEJYQjVEVjlzUXEyOEUwdnZWMnF0dWU1SmNwU21DZ2NISnFpam41bG9WVDJBLw0KUld2Y3VLMmlvc09oRDZVVkR2WWVpOFVhcmhzOW01c1J6TEJ5WFEybVNIN2dlL2Qza01uR0R3cGFUMWRYa0ZOTw0KSFFCU3dmbG1uK0pNVk9jTXFLUVE2Z1dzeW54MTZQem1iSm1HM1RkekFvR0JBS0tpWFk3TDFVMXFleEtsTlZWSw0KbGthNzh4THI0a3dPMDVxYk5XcVYrYlFhTTFFRVFkSDNrZURTWGlLYUdvTVgzRm9ya0pRRXR4ZEo5T1g4VVFMcg0KQzhBZjdTTWZIUUxUTmhnS2RUeHZuZDhpcHc5WXc1a1k0REduY24vZVJRczRnZ1Y1SWgyYi9RUEdzbmR1dzdiVw0KZzRTdlgzUE9iQVZ4K3FzR292cDk3NE5SQW9HQkFKR0txUTRIUjluV0daQllaU2VxeVNXRlVJZ3BqMyt3L3pLLw0KellpOWRHT0ZBcWJNSFB5TGdVMFpKbTZJLzNXSDJ6SndZSTZaY0ZDNE5GMG1MUWpyWXg1NDBIN0ZjSzhpcFVXcw0KTkd4eDU3V0F5K1NKaHRHM2FWYWRQM2kwMENxMytpbGdJYmJtMkxGLzhMUTJNTERFYVpTZGVjZ29kM2dybTVtcA0KeTlsbEJtRHZBb0dCQU1FK2hMVCsyamd1ek1aNHlyUWNDbTNSVzBhRy9kOFMwUnlOQUhpb2dwSHdSUmUxQ2IvbQ0KaHdYeGtiM1cwbDEvQWVPSGxqQ2Y2ZHFCK3Y2NTJjL1NzUFVhYkR3S0JMODZaMENWQldra1k5VEFueXV3dXFycQ0KUlVJM2p1ekFRaEFyTDFJd2ZXdFZMb0JucjdkMDZwL242S2RKaEhRbUY1WURON0s5RGZET2VuYisNCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0t
  etcd-cert: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEWmpDQ0FrNmdBd0lCQWdJVVQ0SGVvS25mL0RqZGhyMUFGSDZDMGR6SDE4b3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3SFRFYk1Ca0dBMVVFQXhNU2JEZ3Vhemh6TG1kcFoyRnVkR2xqTG1sdk1CNFhEVEUzTURVd05ERXhOVGN3DQpNMW9YRFRFM01EVXhNVEV4TlRjek0xb3dLekVwTUNjR0ExVUVBeE1nWlhSalpDMTNiM0pyWlhJdE1pNXNPQzVyDQpPSE11WjJsbllXNTBhV011YVc4d2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURnDQpNcTBYdjZpRGtMZkpGRWd2Q0M0cVdlTk42aHJmRHRTR1QrcW5nWmZwZDcwV0xEbGZoZTErRWFRZisxb2dtQ0lYDQpxRDA4a3ZoZHdxM0xnSDkzb3pCM1lzdHgrUXJHSll5cVZSR3pWYU5mZkVsdy82S29tb2xGWklqK1dqVEdHdVNoDQpoTHp3cHhqbEhWc2toTDFqR29xMXcvL1lDSGc3bG54bElDM3BIaTA0VDhycjFYM3c3SjJ2RHc4bXZaYzAxS2g2DQp0dDNvUVdTcU1PeGMrZlEvUkk2NEswbTk2bUFFVEVDV1NXcmNwWEZMSXZLT0VCNWJlK1ZHMVVKcmhjc0cxOFE2DQpScFhqQnNoeCtHa05KSjJwU3NUekVXZGhZWEhKLzVJTzk3a2tRS2hlcm9VTWNHNE81YWFaZEowdmg2M1ZRMXlODQpaT210empUQlZRNmxSbnB1N0twckFnTUJBQUdqZ1k4d2dZd3dIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHDQpDQ3NHQVFVRkJ3TUNNQjBHQTFVZERnUVdCQlIzdU9wSDRWYy9GcFlWT0M1V2Z0QkMrcHNxK2pBZkJnTlZIU01FDQpHREFXZ0JRVnNZYUFzbTB1VUtoeGZtUnl2WjkwU2VPRUJEQXJCZ05WSFJFRUpEQWlnaUJsZEdOa0xYZHZjbXRsDQpjaTB5TG13NExtczRjeTVuYVdkaGJuUnBZeTVwYnpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQVZ2VDJmQTlKDQpudTBqK016SmxRNlFhQmJrdVdXWWpkei81eFpuWDdncjJxQkxYMTVEM3ZlMmticUpISmhnUTdabWw3Mk91WEp6DQozZ0xualJxd3pIK2hQbTB4RzY1MDgwVjU2VUNWYjZSL0d4bEJBWGZaYm5RSkVMamdwelJkZmtXNDZJZDdEclVpDQoxYTNIMXo5TmZZbTMrZVZseG1Hc2pMTm85ZWRiY29Fd1Q2cGFQcElJd0dVUWx5elFMQUljTGJlVm0zd3M2L20xDQpIeTcrYlJQdDFseWd1czNXQzYxZHBmaklTQ0ErdlI2Vk4rZTFjNGdZT3NxV1hxLy9PTkZyeEdrTUdyd3lJejZQDQpNWTJ6M1VmMWx6UEhrcUZJaHRzS0NCbmM4SVA3M0g1N043UmtzR1VoZDM3a29lYVVML2I3cU9MNmJGcEl0ZkM2DQpvRUlEQ2lYR3BlcHBqQT09DQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  etcd-ca: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEVERDQ0FqU2dBd0lCQWdJVWFxcmRwU3BCMzRvdFUxZDlpNmZ4WHpsa1Noc3dEUVlKS29aSWh2Y05BUUVMDQpCUUF3SFRFYk1Ca0dBMVVFQXhNU2JEZ3Vhemh6TG1kcFoyRnVkR2xqTG1sdk1CNFhEVEUyTVRBeE16RXpNREUxDQpNbG9YRFRJMk1EZ3lNakV6TURJeU1sb3dIVEViTUJrR0ExVUVBeE1TYkRndWF6aHpMbWRwWjJGdWRHbGpMbWx2DQpNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXltMWM2WWQ3bWdwQ25wSXlXZ0hQDQpNY3ZkU1h0L0dMMDI2VjVPL2hEdEo0YjhVTUJnbTAvUVNPVW95TFZXUmF5aUY5c3RQYWpaQjJmTEdSRzh0d0dnDQpvWXJSQTdNRjVJbFZkYXVVWHVUTFZOakNRTERBK29jNElLRVV2RmFPaVhMZjBTNTIySE5ndkFFMEJvVEhvQmREDQo1akhnQk5KZml1MEc0QWp1NDZuUFJxVnkyUHE2bGg2TGtHaVBmT29kMUpxUjYrNDNSUWxrVE5GY3pYTy81Z1lFDQp1NVhzVGpZbHc1UnhuS2ZxNHQzdThwY0lWdUJRalhjYUNGbUF6eU56cm5XQ1FPOTB4Ni9kQS9lWlJock04SXNwDQpuL1NteHlROUhmeTN5T1o0RWlTZk94aXJhalUvZGwrUHVubEZaUXFsTHNsc3VWYmtRbGplUURhSmoveDZkVFBNDQo0d0lEQVFBQm80R0RNSUdBTUE0R0ExVWREd0VCL3dRRUF3SUJCakFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHDQpBMVVkRGdRV0JCUVZzWWFBc20wdVVLaHhmbVJ5dlo5MFNlT0VCREFmQmdOVkhTTUVHREFXZ0JRVnNZYUFzbTB1DQpVS2h4Zm1SeXZaOTBTZU9FQkRBZEJnTlZIUkVFRmpBVWdoSnNPQzVyT0hNdVoybG5ZVzUwYVdNdWFXOHdEUVlKDQpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFNaUFqd0pZTm9haEVFT1JaOGtTM0pUeEhNdVlFbm1RMyt6dTI1dU9laVV5DQpXNkdMTE1WRmFCazE4Qy9uenIyRHozdUtURHNwTFh0YTE5bFJ6UE9kZFdDMDFnSEtmZVpXaDVCMG9PbkQ4VHFIDQpMdjdxTEtMUVJYQmNGY2tNV016c1paR0J1QXdYQXh3SjduV2hOd1FXbFM4UG9BMFVmeTVJRUw3Tm5wcmYwTWpJDQp0UDZEQ04vMDhqU0ZrU3F0TzVkSlVtWit2YjBldEliS3pHTDl1MVl3bzN1VXhGZWxPMm00a2ZzQjMraksxd2FaDQpEMWNDMWJTOGFLUDBMOVp3dzdnTDc5aWZuQmQ1ODhYd3QrVXVYaG0vQlJ4bVdHQWt4M25JR2t4Z01XbnEwZUUzDQo2Qmw3VWJiSFBMQTVhYTMwN0dEM3ZaQngwSlBDYmlhQW9yN0pvUEpaK29jPQ0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==

---

# This manifest installs the calico/node container, as well
# as the Calico CNI plugins and network config on
# each master and worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: calico-node
  namespace: kube-system
  labels:
    k8s-app: calico-node
spec:
  selector:
    matchLabels:
      k8s-app: calico-node
  template:
    metadata:
      labels:
        k8s-app: calico-node
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: |
          [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
           {"key":"CriticalAddonsOnly", "operator":"Exists"}]
    spec:
      hostNetwork: true
      containers:
        # Runs calico/node container on each Kubernetes node.  This
        # container programs network policy and routes on each
        # host.
        - name: calico-node
          image: quay.io/calico/node:v1.1.3
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Choose the backend to use.
            - name: CALICO_NETWORKING_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: calico_backend
            # Disable file logging so `kubectl logs` works.
            - name: CALICO_DISABLE_FILE_LOGGING
              value: "true"
            # Set Felix endpoint to host default action to ACCEPT.
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
            # Configure the IP Pool from which Pod IPs will be chosen.
            - name: CALICO_IPV4POOL_CIDR
              value: "192.168.0.0/16"
            - name: CALICO_IPV4POOL_IPIP
              value: "always"
            # Disable IPv6 on Kubernetes.
            - name: FELIX_IPV6SUPPORT
              value: "false"
            # Set Felix logging to "info"
            - name: FELIX_LOGSEVERITYSCREEN
              value: "info"
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # Auto-detect the BGP IP address.
            - name: IP
              value: ""
          securityContext:
            privileged: true
          resources:
            requests:
              cpu: 250m
          volumeMounts:
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
            - mountPath: /var/run/calico
              name: var-run-calico
              readOnly: false
            - mountPath: /calico-secrets
              name: etcd-certs
        # This container installs the Calico CNI binaries
        # and CNI network config file on each node.
        - name: install-cni
          image: quay.io/calico/cni:v1.8.0
          command: ["/install-cni.sh"]
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # The CNI network config to install on each node.
            - name: CNI_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: cni_network_config
          volumeMounts:
            - mountPath: /host/opt/cni/bin
              name: cni-bin-dir
            - mountPath: /host/etc/cni/net.d
              name: cni-net-dir
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Used by calico/node.
        - name: lib-modules
          hostPath:
            path: /lib/modules
        - name: var-run-calico
          hostPath:
            path: /var/run/calico
        # Used to install CNI.
        - name: cni-bin-dir
          hostPath:
            path: /opt/cni/bin
        - name: cni-net-dir
          hostPath:
            path: /etc/cni/net.d
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets

---

# This manifest deploys the Calico policy controller on Kubernetes.
# See https://github.com/projectcalico/k8s-policy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calico-policy-controller
  namespace: kube-system
  labels:
    k8s-app: calico-policy
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ''
    scheduler.alpha.kubernetes.io/tolerations: |
      [{"key": "dedicated", "value": "master", "effect": "NoSchedule" },
       {"key":"CriticalAddonsOnly", "operator":"Exists"}]
spec:
  # The policy controller can only have a single active instance.
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      name: calico-policy-controller
      namespace: kube-system
      labels:
        k8s-app: calico-policy
    spec:
      # The policy controller must run in the host network namespace so that
      # it isn't governed by policy that would prevent it from working.
      hostNetwork: true
      containers:
        - name: calico-policy-controller
          image: quay.io/calico/kube-policy-controller:v0.5.4
          env:
            # The location of the Calico etcd cluster.
            - name: ETCD_ENDPOINTS
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_endpoints
            # Location of the CA certificate for etcd.
            - name: ETCD_CA_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_ca
            # Location of the client key for etcd.
            - name: ETCD_KEY_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_key
            # Location of the client certificate for etcd.
            - name: ETCD_CERT_FILE
              valueFrom:
                configMapKeyRef:
                  name: calico-config
                  key: etcd_cert
            # The location of the Kubernetes API.  Use the default Kubernetes
            # service for API access.
            - name: K8S_API
              value: "https://api.l8.k8s.gigantic.io:443"
            # Since we're running in the host namespace and might not have KubeDNS
            # access, configure the container's /etc/hosts to resolve
            # kubernetes.default to the correct service clusterIP.
            - name: CONFIGURE_ETC_HOSTS
              value: "true"
          volumeMounts:
            # Mount in the etcd TLS secrets.
            - mountPath: /calico-secrets
              name: etcd-certs
      volumes:
        # Mount in the etcd TLS secrets.
        - name: etcd-certs
          secret:
            secretName: calico-etcd-secrets
```
